=== pgexec/crawlerTjal/json_schemaAlagoas.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "numero_processo": {"type": "string"},
        "classe": {"type": "string"},
        "assunto": {"type": "string"},
        "foro": {"type": "string"},
        "vara": {"type": "string"},
        "juiz": {"type": "string"},
        "distribuicao": {"type": "string"},
        "controle": {"type": "string"},
        "area": {"type": "string"},
        "valor_acao": {"type": "string"},
        "outros_assuntos": {"type": "string"},
        "partes": {
            "type": "object",
            "properties": {
                "autor": {
                    "type": "array",
                    "items": {"type": "object", "properties": {"nome": {"type": "string"}}, "required": ["nome"]}
                },
                "reu": {
                    "type": "array",
                    "items": {"type": "object", "properties": {"nome": {"type": "string"}}, "required": ["nome"]}
                },
                "Testemunha": {
                    "type": "array",
                    "items": {"type": "object", "properties": {"nome": {"type": "string"}}, "required": ["nome"]}
                }
            },
            "required": ["autor", "reu", "Testemunha"]
        },
        "movimentacoes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {"data": {"type": "string", "format": "date"}, "movimento": {"type": "string"}},
                "required": ["data", "movimento"]
            }
        },
        "peticoes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {"data": {"type": "string", "format": "date"}, "tipo": {"type": "string"}},
                "required": ["data", "tipo"]
            }
        },
        "incidentes": {
            "type": "array",
            "items": {"type": "object", "properties": {"incidente": {"type": "string"}}, "required": ["incidente"]}
        },
        "Apensos": {
            "type": "array",
            "items": {"type": "object", "properties": {"apensos": {"type": "string"}}, "required": ["apensos"]}
        },
        "audiencias": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "data": {"type": "string", "format": "date"},
                    "audiencia": {"type": "string"},
                    "situacao": {"type": "string"},
                    "qtPessoas": {"type": "string"}
                },
                "required": ["data", "audiencia", "situacao", "qtPessoas"]
            }
        }
    },
    "required": [
        "numero_processo",
        "classe",
        "assunto",
        "foro",
        "vara",
        "juiz",
        "partes",
        "movimentacoes",
        "peticoes",
        "incidentes",
        "Apensos",
        "audiencias"
    ]
}

=== pgexec/crawlerTjal/0731425-82.2014.8.02.0001.json
{
    "numero_processo": "0731425-82.2014.8.02.0001",
    "classe": "Procedimento Comum Cível",
    "assunto": "Cartão de Crédito",
    "foro": "Foro de Maceió",
    "vara": "3ª Vara Cível da Capital",
    "juiz": "Henrique Gomes de Barros Teixeira",
    "distribuicao": "09/03/2016 às 14:40 - Prevenção",
    "controle": "2016/000222",
    "area": "Cível",
    "valor_acao": "R$         15.000,00",
    "partes": {
        "autor": [
            {
                "nome": "Maria Edite dos Santos Defensor P: Defensoria Pública do Estado de Alagoas"
            }
        ],
        "reu": [
            {
                "nome": "Hipercard Banco Multiplo S/A Advogado: Raoni Souza Drummond Advogado: Eduardo Fraga Advogada: Andrea Freire Tynan"
            }
        ],
        "Testemunha": [
            {
                "nome": "W. dos S. F."
            }
        ]
    },
    "movimentacoes": [
        {
            "data": "19/02/2020",
            "movimento": "Remetido recurso eletrônico ao Tribunal de Justiça/Turma de recurso"
        },
        {
            "data": "10/02/2020",
            "movimento": "Juntada de Documento Nº Protocolo: WMAC.20.70030322-7 Tipo da Petição: Contrarrazões Data: 10/02/2020 18:44"
        },
        {
            "data": "07/01/2020",
            "movimento": "Ato Publicado Relação :0009/2020 Data da Publicação: 08/01/2020 Número do Diário: 2501"
        },
        {
            "data": "06/01/2020",
            "movimento": "Disponibilização no Diário da Justiça Eletrônico Relação: 0009/2020 Teor do ato: Interposto recurso de apelação pela parte autora, intime-se a parte recorrida para apresentar contrarrazões, no prazo de 15 (quinze) dias, conforme o art. 1010,§ 1º do CPC. Se apresentada Apelação Adesiva pela parte recorrida (art.997, §2º do CPC), intime-se a parte contrária para contrarrazões, no prazo de 15 (quinze) dias, nos termos do Art. 1010, §2º do CPC. Caso as contrarrazões do recurso principal ou do adesivo ventilem matérias elencadas no art.1009, §1º do CPC, intime-se o recorrente para se manifestar sobre elas no prazo de 15(quinze) dias, conforme o art. 1009, § 2º, do CPC. Após as providências acima, remetam-se os autos ao Egrégio Tribunal de Justiça. Maceió, 06 de janeiro de 2020. Sandra Buarque Nunes de Lima Analista Advogados(s): Andrea Freire Tynan (OAB 10699/BA), Eduardo Fraga (OAB 10658/BA), Raoni Souza Drummond (OAB 10120A/AL)"
        },
        {
            "data": "06/01/2020",
            "movimento": "Ato Ordinatório - Artigo 162, §4º, CPC Interposto recurso de apelação pela parte autora, intime-se a parte recorrida para apresentar contrarrazões, no prazo de 15 (quinze) dias, conforme o art. 1010,§ 1º do CPC. Se apresentada Apelação Adesiva pela parte recorrida (art.997, §2º do CPC), intime-se a parte contrária para contrarrazões, no prazo de 15 (quinze) dias, nos termos do Art. 1010, §2º do CPC. Caso as contrarrazões do recurso principal ou do adesivo ventilem matérias elencadas no art.1009, §1º do CPC, intime-se o recorrente para se manifestar sobre elas no prazo de 15(quinze) dias, conforme o art. 1009, § 2º, do CPC. Após as providências acima, remetam-se os autos ao Egrégio Tribunal de Justiça. Maceió, 06 de janeiro de 2020. Sandra Buarque Nunes de Lima AnalistaVencimento: 03/02/2020"
        }
    ],
    "peticoes": [
        {
            "data": "09/06/2015",
            "tipo": "Contestação"
        },
        {
            "data": "07/09/2015",
            "tipo": "Réplica"
        },
        {
            "data": "06/06/2017",
            "tipo": "Rol de Testemunhas"
        },
        {
            "data": "20/06/2017",
            "tipo": "Pedido de juntada de documento(s)"
        },
        {
            "data": "23/03/2018",
            "tipo": "Manifestação do defensor público"
        },
        {
            "data": "12/12/2019",
            "tipo": "Recurso de Apelação"
        },
        {
            "data": "10/02/2020",
            "tipo": "Contrarrazões"
        }
    ],
    "incidentes": [
        {
            "incidente": "Não há incidentes, ações incidentais, recursos ou execuções de sentenças vinculados a este processo."
        }
    ],
    "Apensos": [
        {
            "apensos": "Não há processos apensados, entranhados e unificados a este processo."
        }
    ],
    "audiencias": [
        {
            "data": "26/01/2016",
            "audiencia": "Conciliação",
            "situacao": "Realizada",
            "qtPessoas": "2"
        },
        {
            "data": "12/06/2018",
            "audiencia": "Instrução e Julgamento",
            "situacao": "Realizada",
            "qtPessoas": "2"
        }
    ],
    "outros_assuntos": "Procedimento Comum Cível"
}
